### ISSUE TITLE
Port outlier detection from MovinPy

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/movingpandas#129]
In collaboration with https://github.com/giorgostheo

https://github.com/DataStories-UniPi/MovinPy/blob/master/cleanse_and_detect_outliers.py

**Comment by giorgostheo** [comment]
Should the respective implementation package the functionality as a whole (like it does in MovinPy)? More specifically, the MovinPy implementation both drops duplicates and detects and drops outliers (if the user wants the dropped). How should the movingpandas implementation be structured? Also, some info regarding where to put the implementation would be nice (which file that is).

**Comment by anitagraser** [comment]
The trajectory constructor already drops lines with duplicate timestamps:
https://github.com/anitagraser/movingpandas/blob/39a5e3d17a160cbd403e5dd709b1bb48d172921e/movingpandas/trajectory.py#L98 Is that identical to what MovinPy does? 

I think a new class would make sense here. Could be something like TrajectoryCleaner (in a new `trajectory_cleaner.py`). Then we can have an outlier cleaner and - if necessary - a duplicate cleaner.

**Comment by giorgostheo** [comment]
Given that each Trajectory maps to a specific object, yes that is exactly what MovinPy does w.r.t. dropping duplicates. That's why there is no need to add it to the outlier implementation. 

TrajectoryCleaner sounds good.

**Comment by giorgostheo** [comment]
One more question/addition to the discussion:

The new TrajectoryCleaner class (unlike TrajectoryGeneralizer for example) needs at least two arguments (based on the MovinPy implementation) in order to be usable. These are the features based on which the outliers will be discovered, as well as the accompanying alpha/threshold in order to detect the specific outliers on each feature. So:

1. Do we want the TrajectoryCleaner class to be implemented this way, that is using these two arguments?
2. MovinPy supports the detection of outliers on multiple features (supplied as a list). Do we want that? FYI that entails adding checks to figure out if multiple features are provided and whether a set of thresholds is also provided or just one threshold that corresponds to all the features (one alpha value for example for all the features).

In general my main gripe is that making the class both generic enough and usable based on the parameters needed by the outlier detection algorithm that will inherit from it is not really trivial.

**Comment by anitagraser** [comment]
How about creating a base class TrajectoryCleaner and then subclass it for the different features? The user could then pick the cleaner combination they desire. Or would that be very inefficient compared to the MovinPy implementation? 

```
class TrajectoryCleaner:
   def __init__(self, traj):
      ...
   def clean(self, *args):
      ...
```

**Comment by giorgostheo** [comment]
I do not think efficiency is an issue. Adding the *args and **kwargs would solve this issue, but I though that maintaining some kind of consistency between subclasses was something that was sought after. If that is not an issue, will add the base class with the *args **kwargs and I will implement a OutlierCleaner class that works the same way that the MovinPy implementation does. 

Is the multifeature/multithreshold functionality something that we want or should the class func be provided with just one feature-threshold pair?

**Comment by anitagraser** [comment]
How about:
```
OutlierCleaner.clean(features={'feat1': [thresh], 'feat2': [thresh1, thresh2]})
```

**Comment by giorgostheo** [comment]
Ok so some kind of dict that provides the feature:threshold info right? Should I add this to the base class as well instead of the *args **kwargs part? In general, various cleaners will proly be ok using this kind of structure, so future refactoring might not be needed ...

I'll need some assistance regaring the whole testing/coverage thing since I have very little relevant experience .. 👍

**Comment by anitagraser** [comment]
>  so some kind of dict that provides the feature:threshold info right?

Yes, let's try that. 

> I'll need some assistance regaring the whole testing/coverage thing since I have very little relevant experience 

I see. Let's start with tests for the generalizer PR. Then you'll have a better feeling for what is necessary.

**Comment by giorgostheo** [comment]
I have all the need code ready. However, I cannot push right now because all the TDTR changes are on the master branch of my fork, so I cant create a new clean branch easily. 

As soon as the TDTR pr is resolved, I will fix my tree and I push the outlier code.
