### ISSUE TITLE
Potential bug in the DouglasPeuckerGeneralizer class

### ISSUE THREAD

**Issue by DeemanOne** [anitagraser/movingpandas#158]
Hi,
I was researching how to implement a Generalizer class (for the [EPP Method](https://github.com/LuisFe/EPP)), when I stumbled over a potential bug in the DouglasPeuckerGeneralizer (see below for reference). In the [documentation ](https://shapely.readthedocs.io/en/stable/manual.html) of the `simplify` method from shapely it says:

> [...] By default a slower algorithm is used that preserves topology. If preserve topology is set to False the much quicker Douglas-Peucker algorithm is used.

Shouldn't the `simplify ` method then be called with `preserve_topology=False`?

```

class DouglasPeuckerGeneralizer(TrajectoryGeneralizer):
    """
    Generalizes using Douglas-Peucker algorithm.
    tolerance : float
        Distance tolerance
    Examples
    --------
    >>> mpd.DouglasPeuckerGeneralizer(traj).generalize(tolerance=1.0)
    """

    def _generalize_traj(self, traj, tolerance):
        keep_rows = []
        i = 0
        simplified = traj.to_linestring().simplify(tolerance).coords

        for index, row in traj.df.iterrows():
            current_pt = row[traj.get_geom_column_name()]
            if current_pt.coords[0] in simplified:
                keep_rows.append(i)
            i += 1

        new_df = traj.df.iloc[keep_rows]
        new_traj = Trajectory(new_df, traj.id)
        return new_traj

```

**Comment by anitagraser** [comment]
Thank you for raising this issue, Hendrik! I've been thinking about it and I'd expect that - since we apply simplify to an individual linestring - there is no practical difference whether we use preserve_topology or not. 

Everything seems to come down to Geos:

* http://geos.refractions.net/ro/doxygen_docs/html/classgeos_1_1simplify_1_1DouglasPeuckerSimplifier.html
* http://geos.refractions.net/ro/doxygen_docs/html/classgeos_1_1simplify_1_1TopologyPreservingSimplifier.html
