### ISSUE TITLE
relationship to scikit-mobility

### ISSUE THREAD

**Issue by knaaptime** [anitagraser/movingpandas#54]
Hi, thanks for putting this package together! Seems pretty great.

I'm curious about the overall scope and goals of the project. The emphasis on pandas suggests this library is about providing fundamental data structures for data spatio-temporal data analysis. By contrast, the folks over at [scikit-mobility](https://github.com/scikit-mobility/scikit-mobility) seem to have implemented similar data structures, but afaict their emphasis is on *modeling* flows (hence the emphasis on scikit rather than pandas). There may be some differences in the implementations if they support different goals, but since both of these prominent packages are defining a specification for a space-time geodataframe that could become the defacto standard, I'm curious if there's an opportunity for these packages to speak to one another?

**Comment by anitagraser** [comment]
Indeed, I've been in contact with the developers of scikit-mobility since summer 2019. One noteworthy difference is that they build directly on pandas and don't use geopandas. I tried to port their code to geopandas but go stuck. (This is the corresponding branch in my fork: https://github.com/anitagraser/scikit-mobility/tree/geodataframe)

Another implementation difference is that they use inheritance (a TrajDataFrame inherits pandas.DataFrame) while MovingPandas uses composition (a Trajectory has a geopandas.GeoDataFrame).

Converting between movingpandas.Trajectory and skmob.TrajDataFrame shouldn't be too hard.

**Comment by anitagraser** [comment]
For future reference: The fork above has one failing test where slicing a TrajDataFrame returns a GeoDataFrame instead of a TrajDataFrame. 
https://github.com/anitagraser/scikit-mobility/commit/34425e42d63dae4ff80912e41edf2eb648dff13f

However, this seems to have been working correctly when TrajDataFrame was still a regular Pandas DataFrame. If anyone has an idea how to fix that, I'd love to hear it.
