### ISSUE TITLE
[pyopensci-review] Pip installation issue 

### ISSUE THREAD

**Issue by xmnlab** [anitagraser/movingpandas#58]
Currently the pip installation is raising the follow error:

```
21:09 $ pip install movingpandas
ERROR: Could not find a version that satisfies the requirement movingpandas (from versions: none)
ERROR: No matching distribution found for movingpandas
```

**Comment by anitagraser** [comment]
I'm leaning towards removing pip install instructions. 

The error above appears if pip install movingpandas is called in a Python <= 3.6 environment. So this issue is related to #57 

Pip install on Ubuntu with Python 3.7 fails on cartopy with `Proj 4.9.0 must be installed in Conda environment "movingpandas-dev".`. This seems to be a known issue and conda install is recommended instead of pip: https://stackoverflow.com/questions/53697814/using-pip-install-to-install-cartopy-but-missing-proj-version-at-least-4-9-0

**Comment by wendellwt** [comment]
I was able to install the movingpandas package from PyPI (on Linux, and not using conda or anaconda).  Some packages needed custom installations.  The instructions that I used are here: https://devel.ilikecarrots.com/howto-movingpandas.html

**Comment by anitagraser** [comment]
Thank you for the insights @wendellwt! The dependency situation seems very dynamic, particularly with respect to proj versions right now. This makes it hard to keep up.

**Comment by wendellwt** [comment]
I spoke too soon.  Proj-5 compiles and links, but doesn't run ("no such column: publication_date").  It looks like projpy needs Proj-6 or later.  Revised instructions are at: https://cherry.ilikecarrots.com/howto-movingpandas.html

(A while back I tried Anaconda, but it seemed like it took over my entire machine.  Also, I don't have admin privs on several of the machines I use.  That's why I often have to compile everything from sources and install to a user-writable directory.)

**Comment by wendellwt** [comment]
I spoke too soon ^2.  GeoPandas 0.7 is incompatible with MovingPandas.  GeoPandas 0.6 must be used.

**Comment by anitagraser** [comment]
MovingPandas master should already support GeoPandas 0.7. (Changes include https://github.com/anitagraser/movingpandas/pull/50.) I'm working on a new release.

**Comment by wendellwt** [comment]
Yes.  The current git repo works fine with GeoPandas 0.7.  Sorry about that.

**Comment by anitagraser** [comment]
v0.3rc1 has landed on conda-forge https://anaconda.org/conda-forge/movingpandas
