### ISSUE TITLE
about PointCluster

### ISSUE THREAD

**Issue by greatathrun** [anitagraser/movingpandas#79]
I am a Surveying  Engineer and not good at programming. There's something I don't understand. in the process of PointCluster, why the function redistribute_points() is connected after the function insertPoint(). After it clears ALL points in the grid, and re-clusters and increases max_dist *20 , nothing more. The function insertPoint() seems no work!

**Comment by anitagraser** [comment]
Welcome! After all points have been inserted into the grid and cluster centers have been computed, the paper I've implemented here [0] recommends to recompute the assessment of points to the final clusters because this leads to better results overall. 
This is what happens on line 106-107:
https://github.com/anitagraser/movingpandas/blob/210e7d24f233bcaf50a674742e7f1e558dcd48d0/movingpandas/trajectory_aggregator.py#L107 

[0] Andrienko, N., & Andrienko, G. (2011). Spatial generalization and aggregation of massive movement data. IEEE Transactions on visualization and computer graphics, 17(2), 205-219

**Comment by greatathrun** [comment]
Thanks for your reply



---Original---
